INSERT INTO gatunki (nazwa, id_wybiegu) VALUES
('Lew', 16),
('Tygrys', 16),
('Słoń', 3),
('Żyrafa', 11),
('Hipopotam', 2),
('Krokodyl', 2),
('Panda wielka', 7),
('Koala', 13),
('Pawian', 15),
('Flaming', 3),
('Nosorożec', 3),
('Zebra', 2),
('Kangur', 2),
('Orangutan', 10),
('Goryl', 3),
('Żółw olbrzymi', 5),
('Niedźwiedź polarny', 15),
('Wilk szary', 16),
('Lis polarny', 16),
('Jeleń', 14),
('Królik', 3),
('Wiewiórka', 9),
('Szop pracz', 13),
('Skunks', 14),
('Bóbr', 5),
('Wydra europejska', 12),
('Delfin', 15),
('Opos', 6),
('Duża mysz', 12),
('Szczur', 14),
('Nietoperz', 10),
('Łasica', 13),
('Duży kret', 13),
('Jeżozwierz', 9),
('Pancernik', 6),
('Fretka', 15),
('Jeż europejski', 9),
('Duży motyl', 14),
('Świstak', 11),
('Burunduk', 9),
('Kuna domowa', 3),
('Łoś', 15),
('Piżmak', 4),
('Ryjówka', 2),
('Nornik', 14),
('Piesek preriowy', 7),
('Kojot', 14),
('Dingo', 2),
('Hiena cętkowana', 10),
('Szakal', 4),
('Południowy wombat', 9),
('Gepard', 13),
('Lampart', 16),
('Jaguar', 16),
('Pantera', 13),
('Puma', 8),
('Ryś', 10),
('Ryś rudy', 13),
('Kuguar', 14),
('Ocelot', 11),
('Serwal', 10),
('Karakal', 16),
('Cyweta', 11),
('Genet', 16),
('Mangusta', 15),
('Surykatka', 5),
('Gronostaj', 4),
('Rosomak', 4),
('Foka szara', 4),
('Mors', 11),
('Lew morski', 8),
('Mrównik', 4),
('Mrówkojad wielki', 14),
('Duży łuskowiec', 9),
('Kolczatka', 13),
('Dziobak', 10),
('Szpak', 2),
('Walabia', 1),
('Wombat', 7),
('Diabeł tasmański', 11),
('Aksolotl', 2),
('Bilbi', 8),
('Kuoka', 16),
('Dinozaur', 1),
('Duża lotopałanka', 1),
('Wilk workowaty', 3),
('Kuśkus', 10),
('Rekin', 15),
('Pingwin', 2),
('Wąż', 15),
('Surykatka', 6),
('Kanguroszczur', 11),
('Siteks ruczajowy', 12),
('Aligator', 4),
('Północny wombat', 15),
('Dziki kot', 10),
('Duża meduza', 2),
('Duża szynszyla', 11),
('Dorodny szczupak', 9),
('Świnia rzeczna', 1);
