INSERT INTO gatunki (nazwa, id_wybiegu) VALUES
('Lew', 9),
('Tygrys', 4),
('Słoń', 16),
('Żyrafa', 15),
('Hipopotam', 4),
('Krokodyl', 7),
('Panda wielka', 14),
('Koala', 9),
('Pawian', 15),
('Flaming', 11),
('Nosorożec', 12),
('Zebra', 15),
('Kangur', 12),
('Orangutan', 7),
('Goryl', 10),
('Żółw olbrzymi', 11),
('Niedźwiedź polarny', 10),
('Wilk szary', 10),
('Lis polarny', 2),
('Jeleń', 12),
('Królik', 9),
('Wiewiórka', 9),
('Szop pracz', 8),
('Skunks', 16),
('Bóbr', 7),
('Wydra europejska', 1),
('Delfin', 7),
('Opos', 11),
('Mysz', 13),
('Szczur', 1),
('Nietoperz', 1),
('Łasica', 7),
('Kret', 4),
('Jeżozwierz', 11),
('Pancernik', 5),
('Fretka', 12),
('Jeż europejski', 7),
('Motyl', 8),
('Świstak', 3),
('Burunduk', 7),
('Kuna domowa', 11),
('Łoś', 15),
('Piżmak', 2),
('Ryjówka', 6),
('Nornik', 13),
('Piesek preriowy', 9),
('Kojot', 14),
('Dingo', 9),
('Hiena cętkowana', 2),
('Szakal', 11),
('Południowy wombat', 12),
('Gepard', 5),
('Lampart', 10),
('Jaguar', 14),
('Pantera', 11),
('Puma', 9),
('Ryś', 10),
('Ryś rudy', 16),
('Kuguar', 7),
('Ocelot', 3),
('Serwal', 9),
('Karakal', 10),
('Cyweta', 14),
('Genet', 10),
('Mangusta', 14),
('Surikatka', 16),
('Gronostaj', 9),
('Rosomak', 16),
('Foka szara', 16),
('Mors', 3),
('Lew morski', 15),
('Mrównik', 11),
('Mrówkojad wielki', 13),
('Łuskowiec', 3),
('Kolczatka', 3),
('Dziobak', 4),
('Szpak', 5),
('Walabia', 15),
('Wombat', 1),
('Diabeł tasmański', 6),
('Bandikut', 5),
('Bilbi', 9),
('Kuoka', 14),
('Dinozaur', 10),
('Lotopałanka', 16),
('Wilk workowaty', 15),
('Kuśkus', 8),
('Rekin', 9),
('Pingwin', 7),
('Wąż', 12),
('Surykatka', 6),
('Kanguroszczur', 11),
('Siteks ruczajowy', 4),
('Aligator', 9),
('Północny wombat', 5),
('Dziki kot', 6),
('Meduza', 12),
('Szynszyla', 9),
('Armadillo', 4),
('Świnia rzeczna', 15);
