-- tabele

DROP TABLE IF EXISTS plan_tygodnia CASCADE;
DROP TABLE IF EXISTS popisy CASCADE;
DROP TABLE IF EXISTS sprzat_wybieg CASCADE;
DROP TABLE IF EXISTS opiek_gat CASCADE;
DROP TABLE IF EXISTS tren_gat CASCADE;
DROP TABLE IF EXISTS prac_stan CASCADE;
DROP TABLE IF EXISTS zwierzeta CASCADE;
DROP TABLE IF EXISTS gatunki CASCADE;
DROP TABLE IF EXISTS wybiegi CASCADE;
DROP TABLE IF EXISTS strefy CASCADE;
DROP TABLE IF EXISTS stanowiska CASCADE;
DROP TABLE IF EXISTS konta CASCADE;
DROP TABLE IF EXISTS pracownicy CASCADE;
DROP TABLE IF EXISTS godz_otwarcia CASCADE;
DROP VIEW IF EXISTS plan_24h CASCADE;
DROP VIEW IF EXISTS godz_otwarcia CASCADE;

-- funkcje trigger

DROP TRIGGER IF EXISTS pojedynczy_wiersz ON godz_otwarcia CASCADE;
DROP TRIGGER IF EXISTS akt_godz_otwarcia ON godz_otwarcia CASCADE;
DROP TRIGGER IF EXISTS change_zwierzeta ON zwierzeta CASCADE;

DROP FUNCTION IF EXISTS jeden CASCADE;
DROP FUNCTION IF EXISTS check_godz_popisow CASCADE;
DROP FUNCTION IF EXISTS update_licznosc_gatunku CASCADE;
DROP FUNCTION IF EXISTS check_godz_otwarcia CASCADE;

-- zwykle funkcje

DROP FUNCTION IF EXISTS dobry_pesel CASCADE;
